<?php

$products = [
    new Food(
        "Cane",
        "Crocchette Monge",
        "Le crocchette di Monge Salmone e Riso All Breeds Adult sono un alimento completo per cani adulti di tutte le taglie formulato con un'unica fonte proteica: il salmone.",
        "€48,90",
        "assets/img/crocchette1.jpg",
        "Salmone",
        300,
        5,
    ),
    new Food(
        "Gatto",
        "Cibo Umido Felix",
        "Felix Le Ghiottonerie Multipack 44X85G Mixed Selection è una gamma di deliziose ricette per gatti.",
        "€18,99",
        "assets/img/ciboUmido1.jpg",
        "Pollo",
        500,
        1,
    ),
    new Game(
        "Gatto",
        "Yes! Gatto Pallina",
        "Gioco per gatti Zolux Pirata, con catnip in dotazione per attirare l'attenzione dell'animale e invogliarlo a giocare.",
        "€1,90",
        "assets/img/gioco1.jpg",
        "Plastica",
        "Rosso",
        "Palla",
    ),
    new Game(
        "Cane",
        "Gioco Cane Peluche Atlantide",
        "Gioco Cane Peluche Atlantide Pesce Pagliaccio Simpatici e morbidi peluche per cani ispiranti al mondo sottomarino con squeak integrato.",
        "€8,50",
        "assets/img/gioco2.jpg",
        "Cotone",
        "Azzurro",
        "Peluches",
    ),
    new Shelters(
        "Cane",
        "Cuccia per Cane Angolare in Similpelle",
        "La cuccia angolare di colore borgo natural di Luna&Teo della linea Imperial è stata realizzata in similpelle per garantire al tuo cane il massimo comfort grazie ai materiali di ottima qualità.",
        "€79,90",
        "assets/img/cuccia1.jpg",
        "XXL",
        "Angolare",
    ),
    new Shelters(
        "Gatto",
        "Cuccia in Pile Grigio",
        "Soffice cuccia pelosa in grado di offrire a cani e gatti un posticino morbido e accogliente in cui riposarsi.",
        "€25,99",
        "assets/img/cuccia2.jpg",
        "M",
        "Ovale",
    ),
];
